# -*- coding: utf-8 -*-
# 生成天霸霹雳 300 高频词数据
import json

# (en, zh, phonetic, pos, example, example_zh)
V = [
("be","是","/bi/","v.","I want to be a doctor.","我想当医生。"),
("have","有","/hæv/","v.","I have two brothers.","我有两个兄弟。"),
("do","做","/du/","v.","What do you do?","你是做什么的？"),
("go","去","/goʊ/","v.","Let's go to the park.","我们去公园吧。"),
("come","来","/kʌm/","v.","Please come here.","请过来。"),
("get","得到","/gɛt/","v.","Did you get my message?","你收到我的消息了吗？"),
("make","制作","/meɪk/","v.","She can make a cake.","她会做蛋糕。"),
("take","拿","/teɪk/","v.","Take this umbrella with you.","带上这把伞。"),
("give","给","/gɪv/","v.","Give me a minute.","给我一分钟。"),
("see","看见","/si/","v.","I can see the mountain.","我能看见那座山。"),
("look","看","/lʊk/","v.","Look at that bird!","看那只鸟！"),
("say","说","/seɪ/","v.","What did you say?","你说了什么？"),
("tell","告诉","/tɛl/","v.","Tell me the truth.","告诉我真相。"),
("speak","说话","/spik/","v.","Can you speak slowly?","你能说慢点吗？"),
("know","知道","/noʊ/","v.","I know the answer.","我知道答案。"),
("think","想","/θɪŋk/","v.","I think it's a good idea.","我觉得这是个好主意。"),
("want","想要","/wɑnt/","v.","I want a cup of tea.","我想要一杯茶。"),
("need","需要","/nid/","v.","We need more time.","我们需要更多时间。"),
("like","喜欢","/laɪk/","v.","I like this song.","我喜欢这首歌。"),
("love","爱","/lʌv/","v.","I love my family.","我爱我的家人。"),
("eat","吃","/it/","v.","We eat dinner at seven.","我们七点吃晚饭。"),
("drink","喝","/drɪŋk/","v.","Drink more water.","多喝水。"),
("sleep","睡觉","/slip/","v.","I sleep eight hours a day.","我每天睡八小时。"),
("play","玩","/pleɪ/","v.","The children play outside.","孩子们在外面玩。"),
("run","跑","/rʌn/","v.","He runs every morning.","他每天早上跑步。"),
("walk","走","/wɔk/","v.","I walk to school.","我走路去学校。"),
("buy","买","/baɪ/","v.","I want to buy a gift.","我想买个礼物。"),
("sell","卖","/sɛl/","v.","They sell fresh fruit.","他们卖新鲜水果。"),
("open","打开","/ˈoʊpən/","v.","Open the window, please.","请打开窗户。"),
("put","放","/pʊt/","v.","Put the book on the table.","把书放在桌上。"),
("find","找到","/faɪnd/","v.","I can't find my keys.","我找不到钥匙。"),
("lose","丢失","/luz/","v.","Don't lose your ticket.","别丢了你的票。"),
("keep","保持","/kip/","v.","Keep the change.","零钱不用找了。"),
("leave","离开","/liv/","v.","We leave at noon.","我们中午离开。"),
("bring","带来","/brɪŋ/","v.","Bring your friend along.","带你的朋友一起来。"),
("ask","问","/æsk/","v.","May I ask a question?","我能问个问题吗？"),
("help","帮助","/hɛlp/","v.","Can you help me?","你能帮我吗？"),
("meet","遇见","/mit/","v.","Nice to meet you.","很高兴认识你。"),
("wait","等待","/weɪt/","v.","Wait for me here.","在这里等我。"),
("start","开始","/stɑrt/","v.","Let's start the meeting.","我们开始开会吧。"),
("stop","停止","/stɑp/","v.","Stop at the red light.","红灯时停下。"),
("finish","完成","/ˈfɪnɪʃ/","v.","I finish work at six.","我六点下班。"),
("try","尝试","/traɪ/","v.","Try this delicious soup.","尝尝这美味的汤。"),
("read","阅读","/rid/","v.","I read books every night.","我每晚读书。"),
("write","写","/raɪt/","v.","Write your name here.","在这里写你的名字。"),
("listen","听","/ˈlɪsən/","v.","Listen to the music.","听音乐。"),
("hear","听见","/hɪr/","v.","Can you hear me?","你能听见我吗？"),
("watch","观看","/wɑtʃ/","v.","We watch TV together.","我们一起看电视。"),
("wash","洗","/wɑʃ/","v.","Wash your hands first.","先洗手。"),
("cook","做饭","/kʊk/","v.","My father cooks dinner.","我爸爸做晚饭。"),
("drive","开车","/draɪv/","v.","He drives to work.","他开车上班。"),
("send","发送","/sɛnd/","v.","Send me an email.","给我发邮件。"),
("pay","付钱","/peɪ/","v.","I pay by phone.","我用手机付款。"),
("cost","花费","/kɔst/","v.","It costs ten dollars.","它要十美元。"),
("live","生活","/lɪv/","v.","They live in a big city.","他们住在大城市。"),
("feel","感觉","/fil/","v.","I feel happy today.","我今天感觉很开心。"),
("learn","学习","/lɜrn/","v.","I learn English every day.","我每天学英语。"),
("close","关","/kloʊz/","v.","Close the door quietly.","轻轻关门。"),
("sit","坐","/sɪt/","v.","Please sit down.","请坐。"),
("stand","站","/stænd/","v.","Stand up, please.","请站起来。"),
("turn","转动","/tɜrn/","v.","Turn left at the corner.","在拐角处左转。"),
("move","移动","/muv/","v.","We move to a new house.","我们搬去新房子。"),
("change","改变","/tʃeɪndʒ/","v.","Change your clothes.","换衣服。"),
("call","打电话","/kɔl/","v.","Call me tonight.","今晚给我打电话。"),
("show","展示","/ʃoʊ/","v.","Show me your photo.","给我看你的照片。"),
("hold","拿住","/hoʊld/","v.","Hold my hand.","握住我的手。"),
("carry","携带","/ˈkæri/","v.","Carry the bag for me.","帮我拿包。"),
("forget","忘记","/fərˈgɛt/","v.","Don't forget your keys.","别忘了你的钥匙。"),
("remember","记得","/rɪˈmɛmbər/","v.","Remember to call me.","记得给我打电话。"),
("understand","理解","/ˌʌndərˈstænd/","v.","I understand you now.","我现在理解你了。"),
("believe","相信","/bɪˈliv/","v.","I believe you.","我相信你。"),
("hope","希望","/hoʊp/","v.","I hope you feel better.","我希望你好起来。"),
("stay","停留","/steɪ/","v.","Stay here with me.","和我待在这里。"),
("become","变成","/bɪˈkʌm/","v.","She wants to become a nurse.","她想当护士。"),
("grow","生长","/groʊ/","v.","Flowers grow in spring.","花在春天生长。"),
("die","死","/daɪ/","v.","The old tree died.","那棵老树死了。"),
("break","打破","/breɪk/","v.","Don't break the glass.","别打破玻璃。"),
("work","工作","/wɜrk/","v.","I work from home.","我在家工作。"),
("answer","回答","/ˈænsər/","v.","Please answer my question.","请回答我的问题。"),
("clean","打扫","/klin/","v.","I clean my room on Sunday.","我周日打扫房间。"),
]

N = [
("time","时间","/taɪm/","n.","What time is it now?","现在几点了？"),
("day","天","/deɪ/","n.","Have a nice day!","祝你今天愉快！"),
("money","钱","/ˈmʌni/","n.","I need some money.","我需要一些钱。"),
("water","水","/ˈwɔtər/","n.","A glass of water, please.","请给我一杯水。"),
("food","食物","/fud/","n.","The food is delicious.","食物很好吃。"),
("house","房子","/haʊs/","n.","They bought a new house.","他们买了新房子。"),
("home","家","/hoʊm/","n.","I'm going home now.","我现在回家。"),
("family","家庭","/ˈfæməli/","n.","I love my family.","我爱我的家人。"),
("friend","朋友","/frɛnd/","n.","She is my best friend.","她是我最好的朋友。"),
("people","人们","/ˈpipəl/","n.","Many people like music.","许多人喜欢音乐。"),
("man","男人","/mæn/","n.","That man is my uncle.","那个男人是我叔叔。"),
("woman","女人","/ˈwʊmən/","n.","The woman is a doctor.","那个女人是医生。"),
("child","孩子","/tʃaɪld/","n.","The child is playing.","孩子在玩耍。"),
("school","学校","/skul/","n.","I go to school by bus.","我坐公交去学校。"),
("car","汽车","/kɑr/","n.","He drives a red car.","他开一辆红色汽车。"),
("phone","电话","/foʊn/","n.","My phone is ringing.","我的电话在响。"),
("door","门","/dɔr/","n.","Please close the door.","请关门。"),
("room","房间","/rum/","n.","My room is clean.","我的房间很干净。"),
("table","桌子","/ˈteɪbəl/","n.","Dinner is on the table.","晚饭在桌上。"),
("book","书","/bʊk/","n.","This book is interesting.","这本书很有趣。"),
("hand","手","/hænd/","n.","Wash your hands.","洗手。"),
("eye","眼睛","/aɪ/","n.","She has beautiful eyes.","她有美丽的眼睛。"),
("head","头","/hɛd/","n.","My head hurts.","我头疼。"),
("street","街道","/strit/","n.","The street is busy.","街道很繁忙。"),
("city","城市","/ˈsɪti/","n.","Beijing is a big city.","北京是个大城市。"),
("market","市场","/ˈmɑrkɪt/","n.","I buy vegetables at the market.","我在市场买蔬菜。"),
("price","价格","/praɪs/","n.","The price is too high.","价格太高了。"),
("shop","商店","/ʃɑp/","n.","The shop opens at nine.","商店九点开门。"),
("doctor","医生","/ˈdɑktər/","n.","You should see a doctor.","你应该看医生。"),
("thing","东西","/θɪŋ/","n.","What is that thing?","那是什么东西？"),
("world","世界","/wɜrld/","n.","The world is big.","世界很大。"),
("life","生活","/laɪf/","n.","Life is beautiful.","生活是美好的。"),
("name","名字","/neɪm/","n.","What's your name?","你叫什么名字？"),
("place","地方","/pleɪs/","n.","This is a nice place.","这是个好地方。"),
("question","问题","/ˈkwɛstʃən/","n.","I have a question.","我有个问题。"),
("problem","麻烦","/ˈprɑbləm/","n.","No problem!","没问题！"),
("idea","想法","/aɪˈdiə/","n.","That's a good idea.","那是个好主意。"),
("way","方法","/weɪ/","n.","This is the right way.","这是正确的方法。"),
("road","路","/roʊd/","n.","The road is long.","路很长。"),
("weather","天气","/ˈwɛðər/","n.","The weather is nice today.","今天天气很好。"),
("night","夜晚","/naɪt/","n.","Good night!","晚安！"),
("morning","早上","/ˈmɔrnɪŋ/","n.","Good morning!","早上好！"),
("face","脸","/feɪs/","n.","Wash your face.","洗脸。"),
("mouth","嘴","/maʊθ/","n.","Open your mouth.","张开嘴。"),
("hair","头发","/hɛr/","n.","She has long hair.","她有长头发。"),
("clothes","衣服","/kloʊðz/","n.","I need new clothes.","我需要新衣服。"),
("shirt","衬衫","/ʃɜrt/","n.","This shirt is too small.","这件衬衫太小了。"),
("shoes","鞋","/ʃuz/","n.","These shoes are comfortable.","这双鞋很舒服。"),
("bread","面包","/brɛd/","n.","I eat bread for breakfast.","我早餐吃面包。"),
("meat","肉","/mit/","n.","Do you eat meat?","你吃肉吗？"),
("rice","米饭","/raɪs/","n.","We eat rice every day.","我们每天吃米饭。"),
("milk","牛奶","/mɪlk/","n.","I drink milk every morning.","我每天早上喝牛奶。"),
("egg","鸡蛋","/ɛg/","n.","I eat an egg for breakfast.","我早餐吃一个鸡蛋。"),
("tea","茶","/ti/","n.","Would you like some tea?","你想喝茶吗？"),
("coffee","咖啡","/ˈkɔfi/","n.","I drink coffee every day.","我每天喝咖啡。"),
("fruit","水果","/frut/","n.","Eat more fruit.","多吃水果。"),
("vegetable","蔬菜","/ˈvɛdʒtəbəl/","n.","Vegetables are healthy.","蔬菜很健康。"),
("fish","鱼","/fɪʃ/","n.","I like to eat fish.","我喜欢吃鱼。"),
("chicken","鸡肉","/ˈtʃɪkɪn/","n.","We have chicken for dinner.","我们晚饭吃鸡肉。"),
("restaurant","餐厅","/ˈrɛstərɑnt/","n.","Let's eat at that restaurant.","我们去那家餐厅吃饭吧。"),
("hotel","酒店","/hoʊˈtɛl/","n.","We stayed at a hotel.","我们住在一家酒店。"),
("hospital","医院","/ˈhɑspɪtəl/","n.","He went to the hospital.","他去了医院。"),
("bank","银行","/bæŋk/","n.","I need to go to the bank.","我要去银行。"),
("office","办公室","/ˈɔfɪs/","n.","She works in an office.","她在办公室工作。"),
("teacher","老师","/ˈtitʃər/","n.","Our teacher is kind.","我们的老师很和蔼。"),
("student","学生","/ˈstudənt/","n.","He is a good student.","他是个好学生。"),
("job","工作","/dʒɑb/","n.","She found a new job.","她找到了新工作。"),
("news","新闻","/nuz/","n.","I watch the news every day.","我每天看新闻。"),
("music","音乐","/ˈmjuzɪk/","n.","I love listening to music.","我爱听音乐。"),
("movie","电影","/ˈmuvi/","n.","Let's watch a movie.","我们看电影吧。"),
("game","游戏","/geɪm/","n.","We play games together.","我们一起玩游戏。"),
("story","故事","/ˈstɔri/","n.","Tell me a story.","给我讲个故事。"),
("word","单词","/wɜrd/","n.","I learn new words every day.","我每天学新单词。"),
("language","语言","/ˈlæŋgwɪdʒ/","n.","English is a useful language.","英语是门有用的语言。"),
("country","国家","/ˈkʌntri/","n.","China is a big country.","中国是个大国。"),
("animal","动物","/ˈænɪməl/","n.","The panda is a cute animal.","熊猫是可爱的动物。"),
("dog","狗","/dɔg/","n.","I have a little dog.","我有一只小狗。"),
("cat","猫","/kæt/","n.","The cat is sleeping.","猫在睡觉。"),
("tree","树","/tri/","n.","The tree is very tall.","这棵树很高。"),
("flower","花","/ˈflaʊər/","n.","The flowers are beautiful.","这些花很美。"),
("mountain","山","/ˈmaʊntən/","n.","We climbed the mountain.","我们爬了山。"),
("river","河","/ˈrɪvər/","n.","The river is clean.","这条河很干净。"),
("sea","海","/si/","n.","I love the blue sea.","我爱蓝色的大海。"),
("sun","太阳","/sʌn/","n.","The sun is shining.","太阳在照耀。"),
("rain","雨","/reɪn/","n.","The rain is heavy today.","今天雨很大。"),
("week","星期","/wik/","n.","See you next week.","下周见。"),
("year","年","/jɪr/","n.","Happy new year!","新年快乐！"),
("hour","小时","/ˈaʊər/","n.","It takes one hour.","这要花一小时。"),
]

A = [
("good","好的","/gʊd/","adj.","This is a good book.","这是一本好书。"),
("bad","坏的","/bæd/","adj.","The weather is bad today.","今天天气很糟。"),
("big","大的","/bɪg/","adj.","They live in a big house.","他们住在大房子里。"),
("small","小的","/smɔl/","adj.","I have a small gift for you.","我有个小礼物给你。"),
("new","新的","/nu/","adj.","I bought a new phone.","我买了部新手机。"),
("old","老的","/oʊld/","adj.","This is an old building.","这是座老建筑。"),
("hot","热的","/hɑt/","adj.","The tea is very hot.","茶很烫。"),
("cold","冷的","/koʊld/","adj.","It's cold outside.","外面很冷。"),
("happy","开心的","/ˈhæpi/","adj.","I'm so happy today.","我今天很开心。"),
("sad","难过的","/sæd/","adj.","She feels sad.","她感到难过。"),
("beautiful","美丽的","/ˈbjutəfəl/","adj.","What a beautiful view!","多么美丽的景色！"),
("ugly","丑的","/ˈʌgli/","adj.","The old wall is ugly.","那堵旧墙很丑。"),
("fast","快的","/fæst/","adj.","This is a fast car.","这是辆快车。"),
("slow","慢的","/sloʊ/","adj.","The train is slow.","火车很慢。"),
("easy","容易的","/ˈizi/","adj.","This question is easy.","这个问题很简单。"),
("hard","难的","/hɑrd/","adj.","Math is hard for me.","数学对我很难。"),
("high","高的","/haɪ/","adj.","The mountain is high.","山很高。"),
("low","低的","/loʊ/","adj.","The price is low.","价格很低。"),
("long","长的","/lɔŋ/","adj.","She has long hair.","她有长头发。"),
("short","短的","/ʃɔrt/","adj.","The movie is short.","这部电影很短。"),
("right","对的","/raɪt/","adj.","Your answer is right.","你的答案是对的。"),
("wrong","错的","/rɔŋ/","adj.","This is the wrong way.","这条路错了。"),
("rich","富有的","/rɪtʃ/","adj.","He is a rich man.","他是个富人。"),
("poor","穷的","/pʊr/","adj.","The poor family needs help.","那个穷家庭需要帮助。"),
("dirty","脏的","/ˈdɜrti/","adj.","Your shoes are dirty.","你的鞋脏了。"),
("full","满的","/fʊl/","adj.","The cup is full.","杯子是满的。"),
("empty","空的","/ˈɛmpti/","adj.","The box is empty.","盒子是空的。"),
("tired","累的","/ˈtaɪərd/","adj.","I'm tired after work.","下班后我很累。"),
("busy","忙的","/ˈbɪzi/","adj.","She is busy today.","她今天很忙。"),
("important","重要的","/ɪmˈpɔrtənt/","adj.","This is an important meeting.","这是个重要会议。"),
("different","不同的","/ˈdɪfərənt/","adj.","We have different ideas.","我们有不同想法。"),
("same","相同的","/seɪm/","adj.","We wear the same shirt.","我们穿一样的衬衫。"),
("early","早的","/ˈɜrli/","adj.","I get up early.","我起得早。"),
("late","晚的","/leɪt/","adj.","Don't be late for class.","上课别迟到。"),
("young","年轻的","/jʌŋ/","adj.","She looks young.","她看起来很年轻。"),
("strong","强壮的","/strɔŋ/","adj.","He is strong and healthy.","他强壮又健康。"),
("weak","虚弱的","/wik/","adj.","I feel weak today.","我今天感觉虚弱。"),
("cheap","便宜的","/tʃip/","adj.","These apples are cheap.","这些苹果很便宜。"),
("expensive","贵的","/ɪkˈspɛnsɪv/","adj.","The watch is expensive.","这块表很贵。"),
("heavy","重的","/ˈhɛvi/","adj.","The box is heavy.","箱子很重。"),
("light","轻的","/laɪt/","adj.","This bag is light.","这个包很轻。"),
("safe","安全的","/seɪf/","adj.","This place is safe.","这个地方很安全。"),
("dangerous","危险的","/ˈdeɪndʒərəs/","adj.","The road is dangerous.","这条路很危险。"),
("sweet","甜的","/swit/","adj.","The cake is sweet.","蛋糕很甜。"),
("salty","咸的","/ˈsɔlti/","adj.","The soup is too salty.","汤太咸了。"),
("fresh","新鲜的","/frɛʃ/","adj.","The air is fresh.","空气很新鲜。"),
("ready","准备好的","/ˈrɛdi/","adj.","Dinner is ready.","晚饭好了。"),
("free","自由的","/fri/","adj.","The museum is free.","博物馆是免费的。"),
("true","真实的","/tru/","adj.","The story is true.","这个故事是真的。"),
("possible","可能的","/ˈpɑsəbəl/","adj.","It's possible to finish today.","今天完成是可能的。"),
("special","特别的","/ˈspɛʃəl/","adj.","Today is a special day.","今天是特别的一天。"),
("healthy","健康的","/ˈhɛlθi/","adj.","Eat healthy food.","吃健康的食物。"),
("sick","生病的","/sɪk/","adj.","She is sick today.","她今天生病了。"),
("hungry","饿的","/ˈhʌŋgri/","adj.","I'm very hungry.","我很饿。"),
("thirsty","渴的","/ˈθɜrsti/","adj.","I'm thirsty.","我渴了。"),
("angry","生气的","/ˈæŋgri/","adj.","Don't be angry.","别生气。"),
("afraid","害怕的","/əˈfreɪd/","adj.","I'm afraid of dogs.","我怕狗。"),
("surprised","惊讶的","/sərˈpraɪzd/","adj.","I'm surprised to see you.","见到你我真惊讶。"),
("interesting","有趣的","/ˈɪntrəstɪŋ/","adj.","The book is interesting.","这本书很有趣。"),
("quiet","安静的","/ˈkwaɪət/","adj.","Keep quiet, please.","请保持安静。"),
("noisy","吵闹的","/ˈnɔɪzi/","adj.","The street is noisy.","街道很吵闹。"),
("bright","明亮的","/braɪt/","adj.","The room is bright.","房间很明亮。"),
("dark","黑暗的","/dɑrk/","adj.","The room is dark.","房间很暗。"),
("warm","温暖的","/wɔrm/","adj.","The weather is warm.","天气很暖和。"),
("cool","凉爽的","/kul/","adj.","The water is cool.","水很凉。"),
("kind","善良的","/kaɪnd/","adj.","She is kind to everyone.","她对每个人都很善良。"),
("polite","礼貌的","/pəˈlaɪt/","adj.","He is a polite boy.","他是个有礼貌的男孩。"),
("honest","诚实的","/ˈɑnɪst/","adj.","Be honest with me.","对我诚实。"),
("careful","小心的","/ˈkɛrfəl/","adj.","Be careful on the road.","路上要小心。"),
]

ADV = [
("very","非常","/ˈvɛri/","adv.","The movie is very good.","这部电影非常好。"),
("really","真的","/ˈrɪəli/","adv.","I really like it.","我真的很喜欢。"),
("always","总是","/ˈɔlweɪz/","adv.","He is always late.","他总是迟到。"),
("never","从不","/ˈnɛvər/","adv.","I never smoke.","我从不抽烟。"),
("often","经常","/ˈɔfən/","adv.","We often eat out.","我们经常出去吃。"),
("now","现在","/naʊ/","adv.","Do it now.","现在就做。"),
("today","今天","/təˈdeɪ/","adv.","I'm busy today.","我今天很忙。"),
("here","这里","/hɪr/","adv.","Come here, please.","请过来。"),
("there","那里","/ðɛr/","adv.","Put it over there.","把它放那边。"),
("also","也","/ˈɔlsoʊ/","adv.","I also like tea.","我也喜欢茶。"),
("too","也","/tu/","adv.","I like it too.","我也喜欢。"),
("just","刚刚","/dʒʌst/","adv.","I just arrived.","我刚到。"),
("only","只有","/ˈoʊnli/","adv.","I only have ten dollars.","我只有十美元。"),
("still","仍然","/stɪl/","adv.","She is still working.","她还在工作。"),
("again","再次","/əˈgɛn/","adv.","Say it again, please.","请再说一遍。"),
("together","一起","/təˈgɛðər/","adv.","We study together.","我们一起学习。"),
("maybe","也许","/ˈmeɪbi/","adv.","Maybe it will rain.","也许要下雨。"),
("usually","通常","/ˈjuʒuəli/","adv.","I usually get up at seven.","我通常七点起床。"),
("sometimes","有时","/ˈsʌmtaɪmz/","adv.","Sometimes I cook dinner.","有时我做晚饭。"),
("up","向上","/ʌp/","adv.","Look up at the sky.","抬头看天空。"),
("down","向下","/daʊn/","adv.","Sit down, please.","请坐下。"),
("quickly","快速地","/ˈkwɪkli/","adv.","He runs quickly.","他跑得很快。"),
("slowly","慢慢地","/ˈsloʊli/","adv.","Please speak slowly.","请说慢点。"),
]

PREP = [
("in","在…里","/ɪn/","prep.","The pen is in the box.","钢笔在盒子里。"),
("on","在…上","/ɑn/","prep.","The book is on the table.","书在桌上。"),
("at","在(时/地)","/æt/","prep.","I get up at seven.","我七点起床。"),
("to","到","/tu/","prep.","I go to school.","我去学校。"),
("from","从","/frʌm/","prep.","I'm from China.","我来自中国。"),
("with","和…一起","/wɪð/","prep.","I live with my parents.","我和父母一起住。"),
("for","为了","/fɔr/","prep.","This gift is for you.","这个礼物是给你的。"),
("by","通过","/baɪ/","prep.","I go to work by bus.","我坐公交上班。"),
("under","在…下","/ˈʌndər/","prep.","The cat is under the table.","猫在桌子下面。"),
("behind","在…后","/bɪˈhaɪnd/","prep.","The park is behind the school.","公园在学校后面。"),
("before","在…前","/bɪˈfɔr/","prep.","Wash hands before dinner.","饭前洗手。"),
("after","在…后","/ˈæftər/","prep.","We play after class.","我们课后玩。"),
("between","在…间","/bɪˈtwin/","prep.","The shop is between the bank and the park.","商店在银行和公园之间。"),
("about","关于","/əˈbaʊt/","prep.","This book is about animals.","这本书是关于动物的。"),
("of","…的","/ʌv/","prep.","A cup of tea, please.","请来杯茶。"),
]

CONJ = [
("and","和","/ænd/","conj.","I like apples and bananas.","我喜欢苹果和香蕉。"),
("but","但是","/bʌt/","conj.","I want to go, but I'm tired.","我想去，但我累了。"),
("because","因为","/bɪˈkɔz/","conj.","I'm late because of traffic.","因为堵车我迟到了。"),
("if","如果","/ɪf/","conj.","If it rains, stay home.","如果下雨就待在家。"),
("or","或者","/ɔr/","conj.","Do you want tea or coffee?","你要茶还是咖啡？"),
("so","所以","/soʊ/","conj.","I was tired, so I slept.","我累了，所以睡了。"),
("when","当…时","/wɛn/","conj.","Call me when you arrive.","你到了就给我打电话。"),
("while","当…期间","/waɪl/","conj.","I read while waiting.","我边等边看书。"),
("although","虽然","/ɔlˈðoʊ/","conj.","Although it rained, we went out.","虽然下雨了，我们还是出去了。"),
("unless","除非","/ʌnˈlɛs/","conj.","You'll miss it unless you hurry.","除非你快点，否则会错过。"),
]

PRON = [
("I","我","/aɪ/","pron.","I am a student.","我是学生。"),
("you","你","/ju/","pron.","You are my friend.","你是我的朋友。"),
("he","他","/hi/","pron.","He is a doctor.","他是医生。"),
("she","她","/ʃi/","pron.","She is a teacher.","她是老师。"),
("it","它","/ɪt/","pron.","It is a cat.","它是一只猫。"),
("we","我们","/wi/","pron.","We are happy.","我们很开心。"),
("they","他们","/ðeɪ/","pron.","They are my classmates.","他们是我的同学。"),
("this","这个","/ðɪs/","pron.","This is my house.","这是我的房子。"),
("that","那个","/ðæt/","pron.","That is a big tree.","那是一棵大树。"),
("one","一个","/wʌn/","pron.","I have one apple.","我有一个苹果。"),
]

all_words = V + N + A + ADV + PREP + CONJ + PRON

# Build data list
data = []
seen = set()
for en, zh, ph, pos, ex, exzh in all_words:
    key = en.lower()
    if key in seen:
        print(f"DUPLICATE: {en}")
        continue
    seen.add(key)
    data.append({
        "en": en,
        "zh": zh,
        "level": 0,
        "nextReview": 0,
        "timesReviewed": 0,
        "example": ex,
        "phonetic": ph,
        "pos": pos,
        "example_zh": exzh,
    })

print(f"Total unique words: {len(data)}")
print(f"Verbs: {len(V)}, Nouns: {len(N)}, Adj: {len(A)}, Adv: {len(ADV)}, Prep: {len(PREP)}, Conj: {len(CONJ)}, Pron: {len(PRON)}")

# Save as JSON
with open("/Users/piliwang/wordvault/tianba_words.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved to tianba_words.json")
